apiVersion: v1
kind: Service
metadata:
  name: paytrack-service
spec:
  type: NodePort
  selector:
    app: paytrack
  ports:
    - port: 8081        # Port clients call
      targetPort: 8081  # Port inside Pod
      nodePort: 30036   # Port on Minikube node
